site_name: ML for Robotics

nav:
  - Home: index.md
  - Chapter 0: ch0.md
  - Chapter 1: ch1.md
  - Chapter 2: ch2.md
  - Chapter 3: ch3.md
  - Chapter 4: ch4.md
  - Chapter 5: ch5.md
  - Chapter 6: ch6.md
  - Chapter 7: ch7.md
  - Chapter 8: ch8.md
  - Exercise A: projA.md
  - Exercise B: projB.md
  - Exercise C: projC.md
  - Exercise D: projD.md
  - Project 1: proj1.md
  - Project 2: proj2.md
  - Project 3: proj3.md
  - Project 4: proj4.md

  #   - Why Python: ch1/1.md 
  # - Chapter 0:
  #     - Welcome: chapter-0/welcome.md
      # - What You Will Build: chapter-0/build.md
      # - Tools: chapter-0/tools.md
      # - Reading Tips: chapter-0/reading-tips.md
# theme: mkdocs 
theme: readthedocs
markdown_extensions:
  - admonition
  # - pymdownx.details
  # - pymdownx.superfences
